# Generated by Django 5.0.6 on 2024-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_prod',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
